#spring.data.mongodb.uri=mongodb+srv://vigneshreddyyaram11_db_user:ev2OhYVbww3UTjoy@cluster0.2vngb4l.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#server.port=8081
#serer.servlet.context.path=/journal